### ISSUE TITLE
Atmel Studio 7 Support?

### ISSUE THREAD

**Issue by TCWORLD** [cpmcgrath/codealignment#62]
Hi,

I was wondering if this is likely to work with Atmel Studio 7? AS7 is built around the 2015 version of Visual Studio Shell so in theory it should be supported.

I downloaded the V13.1 .vsix file from the VS marketplace and modified the <Installation> section of the manifest to include `<InstallationTarget Version="[7.0]" Id="AtmelStudio" />`. When installing it then detects the AS7 installation and tries to install it. However the install fails with:
```

12/08/2017 11:10:23 - Beginning to install extension to AtmelStudio...
12/08/2017 11:10:23 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
- Visual Studio MPF 11.0
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)

```

I wonder if you've come across anything like this, and whether there is any way of getting codealignment to install into AS7?

**Comment by cpmcgrath** [comment]
Hi,
You'll probably need to contact the Atmel Studio developers for help. At a guess, I would say they are not distributing that version of MPF. try setting the MPF version to something else (10, 12, 13, 14) and see if it helps.
Perhaps try the version before VS2017 support was added. That required the manifest to completely change.

**Comment by cpmcgrath** [comment]
I'm going to close this issue, I'd be happy to accept a pull request if anybody can implement it.

**Comment by TCWORLD** [comment]
In the end I used the V13 release, and edited the manifest file to add V7 to the list, and removed the reference to MPF entirely.
I get the code alignment toolbar in AS7 and it seems to work fine.
